const number=v=>{const m=String(v??'').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?+m[0]:null};
const clean=v=>String(v??'').toLowerCase().replace(/[^a-z0-9]/g,'');
const pair=v=>{const m=String(v??'').match(/(\d+)\s*[-/]\s*(\d+)/);return m?[+m[1],+m[2]]:[null,null]};
const ratio=(a,b,s=100)=>Number.isFinite(a)&&Number.isFinite(b)&&b>0?a/b*s:null;
const assign=(o,k,v)=>{if(Number.isFinite(v))o[k]=+v.toFixed(4)};
const add=(o,k,v)=>{if(Number.isFinite(v))o[k]=(o[k]??0)+v};
const statMap=row=>Object.fromEntries((row?.statistics??[]).map(x=>[clean(x.name||x.label),x.displayValue??x.value]));

export function normalizeNFL({season,teams,games,summaries=[],warnings=[]}){
  const output={season,updatedAt:new Date().toISOString(),sources:{espn:true,weather:'Open-Meteo at simulation time'},warnings,teams:{},games,venues:{}};
  const totals={};
  for(const team of teams){output.teams[team.name]={id:team.id,name:team.name,aliases:[team.abbr,team.name.split(' ').at(-1)],conference:team.division,location:team.location,gamesPlayed:0,dataWeight:0,raw:{},model:{}};output.venues[team.id]=team.location;totals[team.name]={games:0,points:0,allowed:0,homeGames:0,homeWins:0,roadGames:0,roadWins:0,o:{},d:{}}}
  for(const game of games.filter(g=>g.completed))for(const [name,isHome,points,allowed] of [[game.homeTeam,true,game.homePoints,game.awayPoints],[game.awayTeam,false,game.awayPoints,game.homePoints]]){const t=totals[name];if(!t)continue;t.games++;add(t,'points',points);add(t,'allowed',allowed);if(!game.neutralSite){if(isHome){t.homeGames++;if(points>allowed)t.homeWins++}else{t.roadGames++;if(points>allowed)t.roadWins++}}}
  for(const summary of summaries){const rows=summary?.boxscore?.teams??[];if(rows.length<2)continue;for(const row of rows){const name=row.team?.displayName,opp=rows.find(x=>x!==row),t=totals[name];if(!t)continue;for(const [bucket,stats] of [[t.o,statMap(row)],[t.d,statMap(opp)]])for(const [k,v] of Object.entries(stats)){const n=number(v);if(n!==null)add(bucket,k,n);const [a,b]=pair(v);if(a!==null){add(bucket,k+'made',a);add(bucket,k+'attempts',b)}}}}
  for(const team of teams){const out=output.teams[team.name],t=totals[team.name],g=t.games,m=out.model,o=t.o,d=t.d;if(!g)continue;out.gamesPlayed=g;out.dataWeight=+(g/(g+4)).toFixed(4);assign(m,'ppg',t.points/g);assign(m,'pointsAllowed',t.allowed/g);assign(m,'pointDiff',(t.points-t.allowed)/g);assign(m,'homeRecordPct',ratio(t.homeWins,t.homeGames));assign(m,'roadRecordPct',ratio(t.roadWins,t.roadGames));
    const plays=o.totaloffensiveplays||o.totalplays,dplays=d.totaloffensiveplays||d.totalplays;assign(m,'yardsGame',o.totalyards/g);assign(m,'yardsPlay',ratio(o.totalyards,plays,1));assign(m,'passYardsGame',(o.netpassingyards??o.passingyards)/g);assign(m,'rushYardsGame',o.rushingyards/g);assign(m,'yardsRush',ratio(o.rushingyards,o.rushingattempts,1));assign(m,'yardsAllowed',d.totalyards/g);assign(m,'yardsPlayAllowed',ratio(d.totalyards,dplays,1));assign(m,'passYardsAllowed',(d.netpassingyards??d.passingyards)/g);assign(m,'rushYardsAllowed',d.rushingyards/g);assign(m,'yardsRushAllowed',ratio(d.rushingyards,d.rushingattempts,1));
    assign(m,'thirdDownPct',ratio(o.thirddowneffmade,o.thirddowneffattempts));assign(m,'fourthDownPct',ratio(o.fourthdowneffmade,o.fourthdowneffattempts));assign(m,'thirdDownAllowed',ratio(d.thirddowneffmade,d.thirddowneffattempts));assign(m,'redZoneTdPct',ratio(o.redzoneeffmade,o.redzoneeffattempts));assign(m,'redZoneTdAllowed',ratio(d.redzoneeffmade,d.redzoneeffattempts));assign(m,'turnoversGame',o.turnovers/g);assign(m,'interceptions',(d.interceptions??d.passesintercepted)/g);assign(m,'forcedFumbles',d.fumbleslost/g);assign(m,'sacks',(d.sacks??d.sacksyards)/g);assign(m,'sacksAllowed',(o.sacks??o.sacksyards)/g);
    assign(m,'fgPct',ratio(o.fieldgoalsefficiencymade,o.fieldgoalsefficiencyattempts));assign(m,'xpPct',ratio(o.extrapointsefficiencymade,o.extrapointsefficiencyattempts));assign(m,'puntAverage',ratio(o.puntingyards,o.punts,1));assign(m,'playsGame',plays/g);assign(m,'drivesGame',11.2);assign(m,'pointsDrive',(t.points/g)/11.2);assign(m,'oppPointsDrive',(t.allowed/g)/11.2);if(Number.isFinite(m.yardsPlay)&&Number.isFinite(m.yardsPlayAllowed))assign(m,'yppDiff',m.yardsPlay-m.yardsPlayAllowed);if(Number.isFinite(m.thirdDownPct)&&Number.isFinite(m.thirdDownAllowed))assign(m,'thirdDownDiff',m.thirdDownPct-m.thirdDownAllowed);if(Number.isFinite(m.redZoneTdPct)&&Number.isFinite(m.redZoneTdAllowed))assign(m,'redZoneDiff',m.redZoneTdPct-m.redZoneTdAllowed);assign(m,'turnoverDiff',((d.turnovers??0)-(o.turnovers??0))/g)}
  return output;
}
